### ISSUE TITLE
Adding "notification-arns" option to Maven command

### ISSUE THREAD

**Issue by editasmedicinedev** [datasprayio/aws-cdk-maven-plugin#67]
Looking at the documentation, it doesn't seem like there is a way to add a "notification-arns" option when running the deploy command through the maven build?  Is this possible and I'm just not seeing it in the documentation?

**Comment by matusfaro** [comment]
Sorry I missed the notification for your issue. A new version 2.1.0 will be available shortly that accepts and passes down `notificationArns` as a parameter during deploy.
