### ISSUE TITLE
Cloud Assembly error running maven plugin

### ISSUE THREAD

**Issue by mjdinsmore** [datasprayio/aws-cdk-maven-plugin#68]
Using the v2.1.0 maven plugin, when building the code I get an error saying:
`[ERROR] @jsii/kernel.RuntimeError: Error: Cloud assembly schema version mismatch: Maximum schema version supported is 31.0.0, but found 32.0.0`

I have imported the 2.88.0 version of the CDK.  Is this plugin limited to a specific version of the AWS CDK?  If I change to an earlier version of it, I not longer get this error.  If there is a dependency, can this be published somewhere?

**Comment by matusfaro** [comment]
@mjdinsmore Could you try the release v2.1.1? I just bumped to the latest version of JSII yesterday, just forgot to publish the release on GitHub Releases.

**Comment by mjdinsmore** [comment]
That solved it. Thanks for the quick turnaround!
