### ISSUE TITLE
Supporting 36.0.0 cloud assembly schema?

### ISSUE THREAD

**Issue by mjdinsmore** [datasprayio/aws-cdk-maven-plugin#86]
Using the v2.2.5 cdk maven plugin, when building the code I get an error saying:
[ERROR] @jsii/kernel.RuntimeError: Error: Cloud assembly schema version mismatch: Maximum schema version supported is 35.0.0, but found 36.0.0

I have imported the 2.134.0 version of the CDK. Is this plugin limited to a specific version of the AWS CDK? If I change to an earlier version of it, I not longer get this error. If there is a dependency, can this be published somewhere?  Or if there is a way to externally manage this to support newer CDK versions without requiring a new plugin version?

**Comment by matusfaro** [comment]
Hi @mjdinsmore 

Yes, the CDK schema version is tied to aws-cdk version defined in the pom.xml [here](https://github.com/datasprayio/aws-cdk-4j/blob/master/pom.xml#L55) currently at 2.115.0

Let me see if I can easily bump this up now. I will also make a clearer note in the README.

**Comment by matusfaro** [comment]
Try the version 2.2.6 that I just published. it should be in Maven Central in about an hour.

I couldn't extensively test it, if you run into any problems, please open a new issue.

**Comment by mjdinsmore** [comment]
Thank you for the quick fix! Works like a charm!  **Much appreciated!**
